version: '3'
services:
#  mysql:
#    image: mysql:8.0.22
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: openresync
#      MYSQL_USER: user1
#      MYSQL_PASSWORD: password1
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql
#    ports:
#      - 33033:3306
  mariadb:
    image: mariadb:10.3.28-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openresync
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    ports:
      - 33034:3306
